name: tekartik_jquery
version: 0.3.0

description: jquery for dart
publish_to: none
environment:
  sdk: ^3.12.0
dependencies:
  collection: ">=1.19.1"
  pub_semver: ">=2.2.0"
  tekartik_jquery_asset:
    git:
      url: https://github.com/tekartik/jquery_asset.dart
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
    version: '>=0.6.8'
  tekartik_js_utils:
    git:
      url: https://github.com/tekartik/js_utils.dart
      path: js_utils
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
# dependency_overrides:
#   tekartik_utils:
#     path: ../tekartik_utils.dart
#   tekartik_jquery_asset:
#     path: ../tekartik_jquery_asset.dart
dev_dependencies:
  test: ">=1.31.0"
  dev_build: ">=1.1.7+3"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
    version: '>=0.1.0'
  build_runner: ">=2.15.0"
  build_test: '>=0.10.3'
  build_web_compilers: ">=4.4.19"
