name: tekartik_jquery
version: 0.3.0

description: jquery for dart
publish_to: none
environment:
  sdk: ^3.5.0
dependencies:
  collection: '>=1.9.1'
  pub_semver: '>=1.3.0'
  tekartik_jquery_asset:
    git:
      url: https://github.com/tekartik/jquery_asset.dart
      ref: dart3a
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a
    version: '>=0.6.8'
  tekartik_js_utils:
    git:
      url: https://github.com/tekartik/js_utils.dart
      path: js_utils
      ref: dart3a
# dependency_overrides:
#   tekartik_utils:
#     path: ../tekartik_utils.dart
#   tekartik_jquery_asset:
#     path: ../tekartik_jquery_asset.dart
dev_dependencies:
  test: any
  dev_build: '>=0.9.3'
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'
  build_runner: '>=0.10.1'
  build_test: '>=0.10.3'
  build_web_compilers: '>=0.4.2'
